version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://localhost:3000}
    restart: unless-stopped
    volumes:
      # Persist IndexedDB data in a named volume
      - ministry_data:/app/public/.wrangler

volumes:
  ministry_data:
